spring:
  profiles:
    active: dev
  session:
    timeout: 30m
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security:   DEBUG


server:
  servlet:
    session:
      timeout: 30m
